### ISSUE TITLE
When using tag on one stack deployment causing panic

### ISSUE THREAD

**Issue by liangrog** [liangrog/cfctl#16]
(aws) [vagrant@lmw-c845182 amp]$ cfctl stack deploy --tags Name=jump-host --env dev --vault-password-file ~/vaultpassword
[ info ] found s3 bucket cfctl-amp-proteus-dev-templates
panic: send on closed channel

goroutine 101 [running]:
github.com/liangrog/ds/graph/parts.(*Graph).AddVertice.func1.1(0xc000378480, 0xc0004a2740, 0xc0004a92d4, 0xc0004a27c0)
	/home/vagrant/go/pkg/mod/github.com/liangrog/ds@v0.0.0-20190409010058-ef878b422520/graph/parts/graph.go:89 +0x13f
created by github.com/liangrog/ds/graph/parts.(*Graph).AddVertice.func1
	/home/vagrant/go/pkg/mod/github.com/liangrog/ds@v0.0.0-20190409010058-ef878b422520/graph/parts/graph.go:77 +0x13a

**Comment by liangrog** [comment]
also:

panic: sync: negative WaitGroup counter

goroutine 69 [running]:
sync.(*WaitGroup).Add(0xc000037264, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/liangrog/ds/graph/parts.(*Graph).AddVertice.func1.1(0xc000088f00, 0xc00000ec60, 0xc000037264, 0xc00000efe0)
	/home/vagrant/go/pkg/mod/github.com/liangrog/ds@v0.0.0-20190409010058-ef878b422520/graph/parts/graph.go:90 +0x15a
created by github.com/liangrog/ds/graph/parts.(*Graph).AddVertice.func1
	/home/vagrant/go/pkg/mod/github.com/liangrog/ds@v0.0.0-20190409010058-ef878b422520/graph/parts/graph.go:77 +0x13a

**Comment by liangrog** [comment]
The cause of this issue lies in the upstream library liangrog/graph. The bug has been rectified there. The new release will be rebuilt with the fix.
